= SAÉ 3.01 2022-2023
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

toc::[]

== Equipe

Projet réalisé par::

- https://github.com/tobilub04[Tobiasz Strzeszewski : Développeur]
- https://github.com/Sean0203[Sean Escassut : Développeur]
- https://github.com/hackerB200[Eva Tubia : Scrum Master]
- https://github.com/walaedinesekoub[Walaedine Sekoub : Product Owner]

Tutrice enseignante de l'équipe:: 
- mailto:marie-francoise.canut@univ-tlse2.fr[MFC]

== Contexte général

VideoFest est une start-up française implantée à Toulouse et créée en 2021 par les cofondateurs Vignal Alexandre, Dourlent Maxime, Fernandez Mickael et Straputicari Luca. Anciennement tournée sur des gammes d’appareils-photos, VideoFest n’a jamais connu une croissance suffisante pour se démarquer et maintenir son existence dans un
domaine devenu obsolète. Aujourd’hui, les objets technologiques tels que les smartphones ou encore les tablettes implémentent cette fonctionnalité pour une qualité au point. +
L'entreprise a donc décidé de se reconvertir vers la vente de périphériques informatiques afin de répondre à une forte baisse de son chiffre d’affaires. Afin de faciliter cette vente, ils veulent avoir un nouveau site de e-commerce dédié, ce qui leur permettrait de redorer leur image, augmenter leur visibilité, et créer un avantage concurrentiel.

== Réalisations 

Voir documentations utilisateurs

== Gestion de projet & Qualité

- Version courante : https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/releases/tag/1.0[v1.0]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/blob/master/Documentation/Doc_technique_web.adoc[Documentation technique du site web]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/blob/master/Documentation/Doc_utilisateur_web.adoc[Documentation utilisateur du site web]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/blob/master/Documentation/Doc_IoT.adoc[Documentation de l'application IoT]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/blob/master/Documentation/G2A08_ConceptionBD.pdf[Documentation conception de la BD]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/milestone/2[Milestone en cours]
- https://github.com/orgs/IUT-Blagnac/projects/24[Projet du site web]
- https://github.com/orgs/IUT-Blagnac/projects/46[Projet de l'application IoT]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/blob/master/Documentation/Backlog%20Produit.pdf[Backlog produit]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/blob/master/Documentation/Backlog%20Sprint%201.pdf[Backlog sprint 1]
- https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/blob/master/Documentation/Backlog%20Sprint%202.pdf[Backlog sprint 2]

=== Évaluations hebdomadaires

NOTE: Les notes ci-dessous sont mises à jour directement par les enseignants responsables de la compétence 5.

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=881427875&format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=881427875&format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=881427875&format=image"></iframe>
++++
endif::[]

=Sprint 3 retour :
Il manque les liens dans le readme. J'ai les tâches de sprint mais pas les backlogs produis (ils sont seulement en pdf, du coup impossible de lier les tâches aux US du backlog concerné, on perd l'esprit scrum). Les 2 appli sont gérées en même temps, il vaut mieux créer 2 projets distincts.Doc BD ok, il faut démarrer doc user et doc tech pour le site. Rien sur les tests. Release OK.
