INSERT ALL 
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique1', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique2', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique3', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique4', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique5', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique6', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique7', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique8', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique9', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique10', null)
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique1A', 'Electronique1')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique1B', 'Electronique1')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique2A', 'Electronique2')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique2B', 'Electronique2')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique3A', 'Electronique3')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique3B', 'Electronique3')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique4A', 'Electronique4')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique4B', 'Electronique4')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique5A', 'Electronique5')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique5B', 'Electronique5')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique6A', 'Electronique6')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique6B', 'Electronique6')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique7A', 'Electronique7')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique7B', 'Electronique7')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique8A', 'Electronique8')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique8B', 'Electronique8')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique9A', 'Electronique9')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique9B', 'Electronique9')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique10A', 'Electronique10')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('Electronique10B', 'Electronique10')
into CATEGORIE (NOM, CATEGORIEPARENTE) values ('SousElectronique10B1', 'Electronique10B')
into COMMANDE (NUMC, MONTANT, DATEC, PANIER) values (1, 1499.98, DATE '2022-05-01', 1)
into COMMANDE (NUMC, MONTANT, DATEC, PANIER) values (2, 2499.96, DATE '2022-05-02', 2)
into COMMANDE (NUMC, MONTANT, DATEC, PANIER) values (3, 349.99, DATE '2022-05-03', 3)
into COULEUR (NOM) values ('Blanc')
into COULEUR (NOM) values ('Gris')
into COULEUR (NOM) values ('Noir')
into COULEUR (NOM) values ('Rouge')
into COULEUR (NOM) values ('Vert')
into DETAILPANIER (PANIER, PRODUIT, QTE) values (1, 1, 1)
into DETAILPANIER (PANIER, PRODUIT, QTE) values (1, 2, 1)
into DETAILPANIER (PANIER, PRODUIT, QTE) values (2, 1, 2)
into DETAILPANIER (PANIER, PRODUIT, QTE) values (2, 3, 1)
into DETAILPANIER (PANIER, PRODUIT, QTE) values (3, 4, 1)
into DETAILPANIER (PANIER, PRODUIT, QTE) values (3, 5, 1)
into PANIER (NUMP, CLIENT) values (1, 1)
into PANIER (NUMP, CLIENT) values (2, 2)
into PANIER (NUMP, CLIENT) values (3, 3)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (1, 'Jean', 'Bon', 'jeanbon@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '12', '75000', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (3, 'Marie', 'Dupont', 'mariedupont@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '34', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (4, 'Pierre', 'Martin', 'pierremartin@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '56', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (5, 'Claire', 'Durand', 'clairedurand@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '78', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (6, 'Sophie', 'Lefebvre', 'sophielefebvre@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '90', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (7, 'Luc', 'Girard', 'lucgirard@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '11', '75001', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (8, 'Emma', 'Bertrand', 'emmabertrand@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '32', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (9, 'Paul', 'Lebrun', 'paullebrun@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '54', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (10, 'Chloe', 'Rousseau', 'chloerousseau@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '76', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (11, 'Noah', 'Moreau', 'noahmoreau@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '98', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (12, 'Victor', 'Hernandez', 'victorhernandez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '13', '75002', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (13, 'Ines', 'Caron', 'inescaron@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '35', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (14, 'Julien', 'Dupont', 'juliendupont@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '57', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (15, 'Camille', 'Leclerc', 'camilleleclerc@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '79', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (16, 'Lena', 'Gautier', 'lenagautier@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '91', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (17, 'Lucas', 'Meunier', 'lucasmeunier@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '15', '75003', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (18, 'Zoe', 'Blanc', 'zoeblanc@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '37', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (19, 'Alexis', 'Duval', 'alexisduval@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '59', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (20, 'Lola', 'Moreau', 'lolamoreau@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '81', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (21, 'Maxime', 'Dumont', 'maximedumont@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '93', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (22, 'Thomas', 'Lopez', 'thomaslopez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '17', '75004', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (23, 'Lucie', 'Garcia', 'luciegarcia@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '39', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (24, 'Julie', 'Rodriguez', 'julierodriguez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '61', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (25, 'Lea', 'Sanchez', 'leasanchez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '83', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (26, 'Nathan', 'Perez', 'nathanperez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '95', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (27, 'Enzo', 'Martinez', 'enzomartinez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '19', '75005', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (28, 'Chloe', 'Gomez', 'chloegomez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '41', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (29, 'Noah', 'Ruiz', 'noahruiz@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '63', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (30, 'Mila', 'Diaz', 'miladiaz@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '85', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (31, 'Lena', 'Fernandez', 'lenafernandez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '97', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (32, 'Raphaël', 'Moreno', 'raphaelmoreno@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '21', '75006', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (33, 'Clara', 'Muñoz', 'claramunoz@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '43', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (34, 'Clement', 'Gimenez', 'clementgimenez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '65', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (35, 'Inès', 'Jimenez', 'inesjimenez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '87', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (36, 'Adam', 'Ruiz de la Torre', 'adamruizdelatorre@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '99', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (37, 'Nina', 'Alvarez', 'ninaalvarez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '23', '75007', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (38, 'Julia', 'Romero', 'juliaromero@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '45', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (39, 'Nathan', 'Alonso', 'nathanaalonso@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '67', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (40, 'Lina', 'Gonzalez', 'linagonzalez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '89', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (41, 'Alexis', 'Navarro', 'alexisnavarro@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '101', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (42, 'Mila', 'Castro', 'milacastro@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '25', '75008', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (43, 'Léa', 'Suarez', 'leasuarez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '47', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (44, 'Lucas', 'Ortega', 'lucasortega@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '69', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (45, 'Zoe', 'del Castillo', 'zoedelcastillo@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '91', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (46, 'Eva', 'Ortiz', 'evaortiz@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '103', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (47, 'Mathis', 'Rubio', 'mathisrubio@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '27', '75009', 'Paris', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (48, 'Louise', 'Cortes', 'louisecortes@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '49', '31000', 'Toulouse', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (49, 'Noah', 'Lopez', 'noahlopez@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '71', '13000', 'Marseille', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (50, 'Inès', 'Santos', 'inessantos@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '93', '69000', 'Lyon', 'France', 'Admin')
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (51, 'Thomas', 'Castillo', 'thomascastillo@mail.fr', '$2y$10$Jk/wztkPisyl/2ISCWPrtO3oZHk4WEeSIU8XUKJbUDV9dSkNVIJ1i', null, '105', '57000', 'Metz', 'France', null)
into UTILISATEUR (NUMU, NOM, PRENOM, MAIL, MDP, NOMRUE, NUMRUE, CODEPOSTAL, VILLE, PAYS, ADMINISTRATEUR) values (2, 'teste', 'oliviere', 'test@test.test', '$2y$10$PRQ2FzrQ2iFdNZ6zYUJPkOJmLU/zmbNTlEpvkANVm05wnam7daBLS', 'rue de la soupe', '1', '31000', 'Toulouse', 'France', 'Admin')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (1, 'Ordinateur portable', 'REF2', 1.99, 0.15, 'un ordi', 'Dell', 'Electronique1A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (2, 'Ordinateur portable', 'REF1', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique1A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (3, 'Ordinateur portable', 'REF2', 1.99, 0.15, 'un ordi', 'Dell', 'Electronique1A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (4, 'Ordinateur portable', 'REF3', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique1B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (5, 'Ordinateur portable', 'REF4', 9399.99, 0.15, 'un ordi', 'Dell', 'Electronique1B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (6, 'Ordinateur portable', 'REF5', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique2A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (7, 'Ordinateur portable', 'REF6', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique2A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (8, 'Ordinateur portable', 'REF7', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique2B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (9, 'Ordinateur portable', 'REF8', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique2B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (10, 'Ordinateur portable', 'REF9', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique3A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (11, 'Ordinateur portable', 'REF10', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique3A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (12, 'Ordinateur portable', 'REF11', 99.99, 0.15, 'un ordi', 'Dell', 'Electronique3B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (13, 'Ordinateur portable', 'REF12', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique3B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (14, 'Ordinateur portable', 'REF13', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique4A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (15, 'Ordinateur portable', 'REF14', 99.99, 0.15, 'un ordi', 'Dell', 'Electronique4A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (16, 'Ordinateur portable', 'REF15', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique4B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (17, 'Ordinateur portable', 'REF16', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique4B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (18, 'Ordinateur portable', 'REF17', 99.99, 0.15, 'un ordi', 'Dell', 'Electronique5A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (19, 'Ordinateur portable', 'REF18', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique5A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (20, 'Ordinateur portable', 'REF19', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique5B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (21, 'Ordinateur portable', 'REF20', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique5B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (22, 'Ordinateur portable', 'REF21', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique6A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (23, 'Ordinateur portable', 'REF22', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique6A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (24, 'Ordinateur portable', 'REF23', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique6B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (25, 'Ordinateur portable', 'REF24', 999.99, 0.10, 'un ordi', 'Dell', 'Electronique6B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (26, 'Ordinateur portable', 'REF25', 99.99, 0.15, 'un ordi', 'Dell', 'Electronique7A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (27, 'Ordinateur portable', 'REF26', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique7A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (28, 'Ordinateur portable', 'REF27', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique7B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (29, 'Ordinateur portable', 'REF28', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique7B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (30, 'Ordinateur portable', 'REF29', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique8A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (31, 'Ordinateur portable', 'REF30', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique8A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (32, 'Ordinateur portable', 'REF31', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique8B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (33, 'Ordinateur portable', 'REF32', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique8B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (34, 'Ordinateur portable', 'REF33', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique9A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (35, 'Ordinateur portable', 'REF34', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique9A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (36, 'Ordinateur portable', 'REF35', 92996.99, 0.15, 'un ordi', 'Dell', 'Electronique9B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (37, 'Ordinateur portable', 'REF36', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique9B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (38, 'Ordinateur portable', 'REF37', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique10A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (39, 'Ordinateur portable', 'REF38', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique10A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (40, 'Ordinateur portable', 'REF39', 9.99, 0.15, 'un ordi', 'Dell', 'Electronique10B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (41, 'Ordinateur portable', 'REF40', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique10B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (42, 'Ordinateur portable', 'REF41', 9.99, 0.15, 'un ordi', 'Dell', 'Electronique8B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (43, 'Ordinateur portable', 'REF42', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique8B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (44, 'Ordinateur portable', 'REF43', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique9A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (45, 'Ordinateur portable', 'REF44', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique9A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (46, 'Ordinateur portable', 'REF45', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique9B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (47, 'Ordinateur portable', 'REF46', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique9B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (48, 'Ordinateur portable', 'REF47', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique10A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (49, 'Ordinateur portable', 'REF48', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique10A')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (50, 'Ordinateur portable', 'REF49', 999.99, 0.15, 'un ordi', 'Dell', 'Electronique10B')
into PRODUIT (NUMP, NOM, REFERENCE, PRIX, PROMO, DESCRIPTIF, MARQUE, CATEGORIE) values (67, 'Ordinateur portable', 'REF50', 999.99, 0.15, 'un ordi', 'Dell', 'SousElectronique10B1')
into STOCK (COULEUR, PRODUIT, QTE) values ('Noir', 1, 50)
into STOCK (COULEUR, PRODUIT, QTE) values ('Blanc', 1, 25)
into STOCK (COULEUR, PRODUIT, QTE) values ('Gris', 1, 10)
into STOCK (COULEUR, PRODUIT, QTE) values ('Noir', 2, 75)
into STOCK (COULEUR, PRODUIT, QTE) values ('Blanc', 2, 35)
into STOCK (COULEUR, PRODUIT, QTE) values ('Gris', 2, 20)
into STOCK (COULEUR, PRODUIT, QTE) values ('Noir', 3, 100)
into STOCK (COULEUR, PRODUIT, QTE) values ('Blanc', 3, 50)
into STOCK (COULEUR, PRODUIT, QTE) values ('Gris', 3, 25)
into STOCK (COULEUR, PRODUIT, QTE) values ('Rouge', 4, 100)
into STOCK (COULEUR, PRODUIT, QTE) values ('Vert', 4, 50)
into STOCK (COULEUR, PRODUIT, QTE) values ('Noir', 5, 25)
into STOCK (COULEUR, PRODUIT, QTE) values ('Blanc', 5, 15)
into STOCK (COULEUR, PRODUIT, QTE) values ('Gris', 5, 10)