= Documentation utilisateur application IoT
:toc:
:toc-title: Sommaire

Version de l'application : 3 +
Date : 08/01/2023 +
Equipe : 2A-8 +
Client : VidéoFest +
Projet : Gestion entrepôt + 

<<<

== 1. Description du Projet
=== a) Equipe

Product Owner : Walaedine +
Scrum Master : Eva +
Développeurs : Tobiasz et Sean +

=== b) Contexte du projet

VidéoFest est une entreprise qui s'est récemment reconvertie dans la vente de périphériques en ligne, elle possède plusieurs entrepôts dont certaines données doivent être contrôlées. Il existe déjà un réseau de capteurs dans les entrepôts, qui récupèrent plusieurs informations sur les caractéristiques de l'air, comme la température, l'humidité ou la concentration en CO². L'entreprise souhaite aussi pour des raisons de sécurité avoir accès aux données de détection de présence récupérées par les capteurs. Un capteur envoit les informations au serveur toutes les 10 minutes, mais pour le moment ces données ne sont pas exploitées.

=== c) Objectifs du projet

L'objectif de ce projet est de créer une application en Java et Python, qui permettra de configurer les données que l'on veut consulter, qui se connectera au serveur et récupèrera les données voulues, et affichera ces données de façon lisible pour l'utilisateur. On aura donc une partie IHM en Java qui créera le fichier de configuration des données, puis la partie Python fera la connexion et écrira les données dans un autre fichier. Enfin, Java lira ces données et les affichera sur l'IHM.

== 2. Installer l'application
=== a) Prérequis
* Système d'exploitation Debian/Ubuntu
* L'utilisateur qui effectue l'installation doit être sudoer
* Installer les applications dans un répertoire dans lequel on a les droits de créer des nouveaux fichiers

=== b) Installation
Ouvrir un terminal et exécuter les commandes suivantes afin d'installer Python : +
`sudo apt update` +
`sudo apt install python3` +
Garder le terminal ouvert pour installer Java 17 : +
`sudo apt install openjdk-17-jdk openjdk-17-jre` +

L'application python utilise le module paho-mqtt pour communiquer avec les capteurs, il faut donc l'installer avec : +
`pip install paho-mqtt` +

Pour récupérer l'application, naviguez vers la dernière release (ou cliquez https://github.com/IUT-Blagnac/sae3-01-devapp-g2a-8/releases/latest[ici]), et téléchargez le fichier .jar et le fichier .py . +
Placer ces deux fichiers dans le même répertoire. +

== 3. Utiliser l'application

Ouvrir un terminal et se placer dans le même répertoire que l'aplication java avec la commande `cd <chemin du répertoire>`. Lancer l'application Java avec la commande `java -jar [nom_du_jar].jar`.
